# use this file to set variables and paths that the program relies on

# path variable to ns-3 location
NS-3_PATH: /home/mike/apps/ns-allinone-3.26/ns-3.26

# path variable to script output location
SCRIPT_DEST: temp/scripts

# path to store various temporary output (like container config files)
TEMP_DIR: temp

# path variable to store container output
OUTPUT_DEST: temp/output

# default node type to use
NODE_TYPE: ubuntu xenial
